### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by Lavreek** [SolatK/PHPtest#3]
![image](https://github.com/SolatK/PHPtest/assets/38787113/f370b179-7df6-47ee-8ec8-e2c6df149565)
![image](https://github.com/SolatK/PHPtest/assets/38787113/b40b29b6-fe55-498d-afd5-a3e8dc4e5707)
![image](https://github.com/SolatK/PHPtest/assets/38787113/1e8f0a75-8cc6-47e7-98f0-05979714c6aa)
![image](https://github.com/SolatK/PHPtest/assets/38787113/9dde265e-9455-43fe-b2fb-fdbecb1b6318)
[words.txt](https://github.com/SolatK/PHPtest/files/13450948/words.txt)
![image](https://github.com/SolatK/PHPtest/assets/38787113/30af7c1c-f611-4125-9998-d0d5cc4fbaf8)
Не работает
[raw.githubusercontent.com_danakt_russian-words_master_russian.txt](https://github.com/SolatK/PHPtest/files/13450954/raw.githubusercontent.com_danakt_russian-words_master_russian.txt)

**Comment by SolatK** [comment]
Нужно проверять дубликаты слов?

**Comment by SolatK** [comment]
> ![image](https://user-images.githubusercontent.com/38787113/285232977-f370b179-7df6-47ee-8ec8-e2c6df149565.png) ![image](https://user-images.githubusercontent.com/38787113/285233039-b40b29b6-fe55-498d-afd5-a3e8dc4e5707.png) ![image](https://user-images.githubusercontent.com/38787113/285234200-1e8f0a75-8cc6-47e7-98f0-05979714c6aa.png) ![image](https://user-images.githubusercontent.com/38787113/285234664-9dde265e-9455-43fe-b2fb-fdbecb1b6318.png) [words.txt](https://github.com/SolatK/PHPtest/files/13450948/words.txt) ![image](https://user-images.githubusercontent.com/38787113/285234970-30af7c1c-f611-4125-9998-d0d5cc4fbaf8.png) Не работает [raw.githubusercontent.com_danakt_russian-words_master_russian.txt](https://github.com/SolatK/PHPtest/files/13450954/raw.githubusercontent.com_danakt_russian-words_master_russian.txt)

В файле так слова и написаны с дубикатами, а в задании про фильтрацию дубликатов не слова. Так же не ясно что не так на двух последних скриншотах.

**Comment by Lavreek** [comment]
Тестовое задание не выполнено

**Comment by Lavreek** [comment]
Слова "га га га" и множественное клонирование других слов, стало результатом обработки файла "[raw.githubusercontent.com_danakt_russian-words_master_russian.txt](https://github.com/SolatK/PHPtest/files/13450954/raw.githubusercontent.com_danakt_russian-words_master_russian.txt)". Далее я решил убрать все переносы строк, и строка из множества слов, стала одним словом. Количество букв перестало обновляться работу формы проверить не удалось т.к. ничего более не обновлялось, предыдущая библиотека букв и слов не стиралась.

**Comment by SolatK** [comment]
> Слова "га га га" и множественное клонирование других слов, стало результатом обработки файла "[raw.githubusercontent.com_danakt_russian-words_master_russian.txt](https://github.com/SolatK/PHPtest/files/13450954/raw.githubusercontent.com_danakt_russian-words_master_russian.txt)". Далее я решил убрать все переносы строк, и строка из множества слов, стала одним словом. Количество букв перестало обновляться работу формы проверить не удалось т.к. ничего более не обновлялось, предыдущая библиотека букв и слов не стиралась.

Теперь понятно, я просто решил что на том скриншоте очередной файл для тестирования, а не результат работы по словарю.
